title: Faris Irsyadi
logo: /assets/img/countergram-sv-face.jpg
#description: Senior Lecturer | AI & Data Analytics in Energy | Smart Grid & Renewable Energy Solutions  
#show_downloads: true
theme: jekyll-theme-minimal  
